fixing a bug ``` Error: Invalid function argument
  on .terraform/modules/asg/main.tf line 468, in resource "aws_autoscaling_group" "idc":
 468:             instance_type     = lookup(override.value, "instance_type", null)
    ├────────────────
    │ override.value is tuple with 6 elements

Invalid value for "inputMap" parameter: lookup() requires a map as the first argument.

Error: Invalid function argument

  on .terraform/modules/asg/main.tf line 469, in resource "aws_autoscaling_group" "idc":
 469:             weighted_capacity = lookup(override.value, "weighted_capacity", null)
    ├────────────────
    │ override.value is tuple with 6 elements

Invalid value for "inputMap" parameter: lookup() requires a map as the first argument.
```